### PR TITLE
Use `dist: precise` for PHP 5.3

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Review by miya0001 — DISMISSED** [review]

**Comment by danielbachhuber** [comment]
I'm not sure why Travis is failing :(

**Comment by miya0001** [comment]
I tried those tests on Docker with PHP 5.3.
All tests were passed.


Actually, I developed a Docker image which is installed PHP 5.2-7.1 + PHPUnit. 😉 
* https://hub.docker.com/r/miya0001/phpenv/tags/
* https://github.com/miya0001/docker-phpenv

**Comment by gitlost** [comment]
It's just an ordering issue, the first check in `features/find.feature:3` needs to be split into 2 "should contain:"s.

**Comment by danielbachhuber** [comment]
Used `sort` for consistency 3d321f7c7a09afdc9c51184f25ca804400b0bd86

**Pull request merged**
